// Code generated by MockGen. DO NOT EDIT.
// Source: C:/Users/chshe/go/src/github.com/cshealy/sync-sandbox/data/api.go

// Package data is a generated GoMock package.
package data

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockExternalAPI is a mock of ExternalAPI interface
type MockExternalAPI struct {
	ctrl     *gomock.Controller
	recorder *MockExternalAPIMockRecorder
}

// MockExternalAPIMockRecorder is the mock recorder for MockExternalAPI
type MockExternalAPIMockRecorder struct {
	mock *MockExternalAPI
}

// NewMockExternalAPI creates a new mock instance
func NewMockExternalAPI(ctrl *gomock.Controller) *MockExternalAPI {
	mock := &MockExternalAPI{ctrl: ctrl}
	mock.recorder = &MockExternalAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockExternalAPI) EXPECT() *MockExternalAPIMockRecorder {
	return m.recorder
}

// GetBearerToken mocks base method
func (m *MockExternalAPI) GetBearerToken() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBearerToken")
	ret0, _ := ret[0].(error)
	return ret0
}

// GetBearerToken indicates an expected call of GetBearerToken
func (mr *MockExternalAPIMockRecorder) GetBearerToken() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBearerToken", reflect.TypeOf((*MockExternalAPI)(nil).GetBearerToken))
}
