version: '2.0'
services:
  # service to compile proto files
  # https://github.com/znly/docker-protobuf
  protoc:
    image: znly/protoc:0.4.0
    container_name: "protoc"
    working_dir: "/code/proto"
    entrypoint: ["sh", "./protoc.sh"]
    volumes:
      - ./:/code

  sync-sandbox-api:
    image: sync-sandbox:1.0
    container_name: "sync-sandbox-api"
    environment:
      - GATEWAY_PORT=8080
      - SERVER_PORT=50051
    ports:
      - 8080:8080
      - 50051:50051
