version: '2.0'
services:
  # service to compile proto files
  # https://github.com/znly/docker-protobuf
  protoc:
    image: znly/protoc:0.4.0
    container_name: "protoc"
    working_dir: "/code/proto"
    entrypoint: ["sh", "./protoc.sh"]
    volumes:
      - ./:/code

  gomock:
    image: pricec/gomock:1.3.1
    container_name: "gomock"
    working_dir: "/go/src/app"
    entrypoint: ["mockgen", "-source=./data/api.go", "-destination=./data/mocks/dao.go", "-package=data"]
    volumes:
    - ./:/go/src/app

  sync-sandbox-api:
    image: sync-sandbox:1.0
    container_name: "sync-sandbox-api"
    env_file:
      - ~/dev.env
      # The following variables should be setup locally as your auth credentials:
      # SPOTIFY_USERNAME
      # SPOTIFY_PASSWORD
    environment:
      - LOG_LEVEL=info
      - GATEWAY_PORT=8080
      - SERVER_PORT=50051
      - SPOTIFY_PLAYLIST_ID=5G34TWU6P2i19eYWzrpj8M
    ports:
      - 8080:8080

  sync-sandbox-client:  
    image: sync-sandbox-client:1.0
    container_name: "sync-sandbox-client"
    environment:
      - LOG_LEVEL=info
      - SERVER_PORT=50051

  # http://localhost:8081/swagger/
  swagger-docs:
    image: swaggerapi/swagger-ui:v3.25.3
    container_name: swagger-docs
    environment: 
      - SWAGGER_JSON=/foo/sync.swagger.json
      - BASE_URL=/swagger 
    ports: 
      - 8081:8080
    volumes:
      - ./proto:/foo
