version: '2.0'
services:
  # service to compile proto files
  # https://github.com/znly/docker-protobuf
  protoc:
    image: znly/protoc:0.4.0
    container_name: "protoc"
    working_dir: "/code/proto"
    command: ["--go_out=plugins=grpc:.", "-I.", "./sync.proto"]
    volumes:
      - ./:/code

  sync-sandbox-api:
    image: sync-sandbox:1.0
    container_name: "sync-sandbox-api"
    ports:
    - 50051:50051
